export interface Process {
    id: string;
    status: 'Finalizado' | 'Sobrestado' | 'Aguardando área técnica' | 'Área técnica retornou';
    nup: string;
    tipo: 'novo' | 'atualizacao';
    relatorio: string;
    assunto: string;
    observacoes: string | null;
}

export const mockProcesses: Process[] = [
    {
        id: '1',
        status: 'Aguardando área técnica',
        nup: '25000.847293/2024-17',
        tipo: 'novo',
        relatorio: 'Relatório nº 897, mai/2024',
        assunto: 'Tratamento da hepatite C crônica com antivirais de ação direta',
        observacoes: 'Aguardando retorno da área técnica desde mai/2024',
    },
    {
        id: '2',
        status: 'Aguardando área técnica',
        nup: '25000.391847/2021-52',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1086, fev/2026',
        assunto: 'Protocolo de hipertensão arterial sistêmica',
        observacoes: null,
    },
    {
        id: '3',
        status: 'Aguardando área técnica',
        nup: '25000.726481/2025-09',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1.077, dez/2025',
        assunto: 'Terapia biológica para artrite reumatoide',
        observacoes: 'Revisão de critérios de inclusão em andamento',
    },
    {
        id: '4',
        status: 'Aguardando área técnica',
        nup: '25000.058329/2019-83',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 453, mai/2019',
        assunto: 'Rastreamento de câncer colorretal',
        observacoes: 'Nemo enim ipsam voluptatem quia voluptas sit',
    },
    {
        id: '5',
        status: 'Sobrestado',
        nup: '25000.914673/2023-41',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1074, dez/2025',
        assunto: 'Diagnóstico e tratamento da doença de Parkinson',
        observacoes: null,
    },
    {
        id: '6',
        status: 'Sobrestado',
        nup: '25000.283751/2022-68',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1076, dez/2025',
        assunto: 'Manejo da insuficiência cardíaca com fração de ejeção reduzida',
        observacoes: null,
    },
    {
        id: '7',
        status: 'Área técnica retornou',
        nup: '25000.647029/2022-34',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1085, fev/2026',
        assunto: 'Tratamento da asma grave refratária',
        observacoes: null,
    },
    {
        id: '8',
        status: 'Área técnica retornou',
        nup: '25000.519384/2021-77',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1084, fev/2026',
        assunto: 'Protocolo de fibromialgia',
        observacoes: 'Atualização dos critérios diagnósticos pendente',
    },
    {
        id: '9',
        status: 'Finalizado',
        nup: '25000.762840/2025-15',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1023, jul/2025',
        assunto: 'Diagnóstico e tratamento da esclerose múltipla',
        observacoes: 'Publicado no DOU em 15/07/2025',
    },
    {
        id: '10',
        status: 'Finalizado',
        nup: '25000.438291/2022-56',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 732, mai/2022',
        assunto: 'Terapia renal substitutiva para doença renal crônica',
        observacoes: 'Quis nostrum exercitationem ullam corporis suscipit',
    },
    {
        id: '11',
        status: 'Finalizado',
        nup: '25000.873614/2021-29',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 762, ago/2022',
        assunto: 'Protocolo de oncologia — câncer de mama',
        observacoes: 'Quia consequuntur magni dolores eos qui ratione',
    },
    {
        id: '12',
        status: 'Finalizado',
        nup: '25000.194758/2021-43',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 733, mai/2022',
        assunto: 'Tratamento da doença de Crohn',
        observacoes: 'Publicado. Revisão agendada para 2027.',
    },
    {
        id: '13',
        status: 'Finalizado',
        nup: '25000.536921/2024-88',
        tipo: 'novo',
        relatorio: 'Relatório nº 981, mar/2025',
        assunto: 'Diagnóstico de retinose pigmentária',
        observacoes: 'Eaque ipsa quae ab illo inventore veritatis',
    },
    {
        id: '14',
        status: 'Sobrestado',
        nup: '25000.071483/2020-61',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 612, jun/2021',
        assunto: 'Diagnóstico e tratamento do transtorno do espectro autista',
        observacoes: 'Sobrestado aguardando parecer jurídico',
    },
    {
        id: '15',
        status: 'Área técnica retornou',
        nup: '25000.923756/2023-39',
        tipo: 'novo',
        relatorio: 'Relatório nº 1031, ago/2025',
        assunto: 'Tratamento da osteoporose pós-menopausa',
        observacoes: 'Nemo enim ipsam voluptatem quia voluptas sit',
    },
    {
        id: '16',
        status: 'Finalizado',
        nup: '25000.183492/2018-27',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 421, jan/2018',
        assunto: 'Protocolo de doença de Gaucher',
        observacoes: null,
    },
    {
        id: '17',
        status: 'Finalizado',
        nup: '25000.349017/2019-54',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 502, nov/2019',
        assunto: 'Diagnóstico e tratamento da anemia falciforme',
        observacoes: 'Revisão publicada com inclusão de hidroxiureia pediátrica',
    },
    {
        id: '18',
        status: 'Sobrestado',
        nup: '25000.607134/2023-72',
        tipo: 'novo',
        relatorio: 'Relatório nº 945, set/2023',
        assunto: 'Rastreamento do câncer de próstata',
        observacoes: 'Aguardando evidências adicionais de ensaios clínicos',
    },
    {
        id: '19',
        status: 'Aguardando área técnica',
        nup: '25000.482936/2025-03',
        tipo: 'novo',
        relatorio: 'Relatório nº 1079, jan/2026',
        assunto: 'Protocolo da síndrome de Cushing',
        observacoes: null,
    },
    {
        id: '20',
        status: 'Finalizado',
        nup: '25000.715803/2020-48',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 634, dez/2020',
        assunto: 'Tratamento da hipercolesterolemia familiar',
        observacoes: null,
    },
    {
        id: '21',
        status: 'Área técnica retornou',
        nup: '25000.294571/2024-66',
        tipo: 'novo',
        relatorio: 'Relatório nº 1003, jan/2025',
        assunto: 'Diagnóstico de fenilcetonúria',
        observacoes: 'Revisão dos critérios de triagem neonatal em análise',
    },
    {
        id: '22',
        status: 'Finalizado',
        nup: '25000.839246/2019-31',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 519, fev/2020',
        assunto: 'Protocolo de mucopolissacaridose tipo I',
        observacoes: null,
    },
    {
        id: '23',
        status: 'Aguardando área técnica',
        nup: '25000.561804/2025-88',
        tipo: 'novo',
        relatorio: 'Relatório nº 1082, fev/2026',
        assunto: 'Tratamento do câncer de pulmão não pequenas células',
        observacoes: 'Solicitação de dados complementares enviada em fev/2026',
    },
    {
        id: '24',
        status: 'Sobrestado',
        nup: '25000.127649/2022-15',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 789, out/2022',
        assunto: 'Protocolo de imunodeficiências primárias',
        observacoes: null,
    },
    {
        id: '25',
        status: 'Finalizado',
        nup: '25000.403827/2021-97',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 701, jan/2022',
        assunto: 'Tratamento da esquizofrenia refratária',
        observacoes: 'Incluída clozapina como alternativa terapêutica',
    },
    {
        id: '26',
        status: 'Área técnica retornou',
        nup: '25000.856392/2023-50',
        tipo: 'novo',
        relatorio: 'Relatório nº 963, nov/2023',
        assunto: 'Protocolo de fibrose cística',
        observacoes: 'Moduladores de CFTR sob análise técnica',
    },
    {
        id: '27',
        status: 'Finalizado',
        nup: '25000.218475/2018-63',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 388, mar/2018',
        assunto: 'Diagnóstico e tratamento da doença de Wilson',
        observacoes: null,
    },
    {
        id: '28',
        status: 'Finalizado',
        nup: '25000.674930/2022-82',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 811, dez/2022',
        assunto: 'Tratamento da leucemia mieloide crônica',
        observacoes: 'Imatinibe mantido como primeira linha',
    },
    {
        id: '29',
        status: 'Sobrestado',
        nup: '25000.039512/2024-44',
        tipo: 'novo',
        relatorio: 'Relatório nº 967, jan/2024',
        assunto: 'Protocolo de dor crônica não oncológica',
        observacoes: 'Sobrestado para harmonização com protocolo internacional',
    },
    {
        id: '30',
        status: 'Aguardando área técnica',
        nup: '25000.782341/2025-26',
        tipo: 'novo',
        relatorio: 'Relatório nº 1075, dez/2025',
        assunto: 'Diagnóstico e síndrome de Down — suporte multidisciplinar',
        observacoes: null,
    },
    {
        id: '31',
        status: 'Finalizado',
        nup: '25000.956207/2020-19',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 648, fev/2021',
        assunto: 'Tratamento do linfoma difuso de grandes células B',
        observacoes: null,
    },
    {
        id: '32',
        status: 'Área técnica retornou',
        nup: '25000.341086/2023-57',
        tipo: 'novo',
        relatorio: 'Relatório nº 952, out/2023',
        assunto: 'Protocolo de acromegalia',
        observacoes: 'Análogos da somatostatina incluídos na proposta revisada',
    },
    {
        id: '33',
        status: 'Finalizado',
        nup: '25000.629158/2019-76',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 537, abr/2020',
        assunto: 'Diagnóstico e tratamento da miastenia gravis',
        observacoes: null,
    },
    {
        id: '34',
        status: 'Aguardando área técnica',
        nup: '25000.487623/2026-02',
        tipo: 'novo',
        relatorio: 'Relatório nº 1088, mar/2026',
        assunto: 'Tratamento da psoríase em placa moderada a grave',
        observacoes: 'Processo aberto em mar/2026. Aguardando análise inicial.',
    },
    {
        id: '35',
        status: 'Finalizado',
        nup: '25000.104839/2021-65',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 713, fev/2022',
        assunto: 'Protocolo de transplante hepático',
        observacoes: null,
    },
    {
        id: '36',
        status: 'Sobrestado',
        nup: '25000.873021/2023-38',
        tipo: 'novo',
        relatorio: 'Relatório nº 958, out/2023',
        assunto: 'Diagnóstico de doenças lisossômicas',
        observacoes: 'Aguardando publicação de RDC regulamentadora',
    },
    {
        id: '37',
        status: 'Área técnica retornou',
        nup: '25000.260947/2024-91',
        tipo: 'novo',
        relatorio: 'Relatório nº 994, out/2024',
        assunto: 'Tratamento da hidradenite supurativa',
        observacoes: 'Adalimumabe em revisão para inclusão como segunda linha',
    },
    {
        id: '38',
        status: 'Finalizado',
        nup: '25000.538164/2020-37',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 659, mar/2021',
        assunto: 'Protocolo da síndrome de Prader-Willi',
        observacoes: null,
    },
    {
        id: '39',
        status: 'Aguardando área técnica',
        nup: '25000.916403/2025-74',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1070, nov/2025',
        assunto: 'Diagnóstico e tratamento do lúpus eritematoso sistêmico',
        observacoes: null,
    },
    {
        id: '40',
        status: 'Finalizado',
        nup: '25000.374582/2018-90',
        tipo: 'novo',
        relatorio: 'Relatório nº 402, jun/2018',
        assunto: 'Tratamento de diabetes mellitus tipo 2 com inibidores de SGLT2',
        observacoes: 'Publicado. Dapagliflozina e empagliflozina incluídas.',
    },
];
