export interface Process {
    id: string;
    status: 'Finalizado' | 'Sobrestado' | 'Aguardando área técnica' | 'Área técnica retornou';
    nup: string;
    tipo: 'novo' | 'atualizacao';
    relatorio: string;
    assunto: string;
    observacoes: string | null;
}

export const mockProcesses: Process[] = [
    {
        id: '1',
        status: 'Aguardando área técnica',
        nup: '25000.847293/2024-17',
        tipo: 'novo',
        relatorio: 'Relatório nº 897, mai/2024',
        assunto: 'Lorem ipsum dolor sit amet consectetur',
        observacoes: 'Ut enim ad minim veniam quis nostrud exercitation',
    },
    {
        id: '2',
        status: 'Aguardando área técnica',
        nup: '25000.391847/2021-52',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1086, fev/2026',
        assunto: 'Sed do eiusmod tempor incididunt ut labore',
        observacoes: null,
    },
    {
        id: '3',
        status: 'Aguardando área técnica',
        nup: '25000.726481/2025-09',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1.077, dez/2025',
        assunto: 'Duis aute irure dolor in reprehenderit voluptate',
        observacoes: 'Excepteur sint occaecat cupidatat non proident',
    },
    {
        id: '4',
        status: 'Aguardando área técnica',
        nup: '25000.058329/2019-83',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 453, maio/2019',
        assunto: 'Sunt in culpa qui officia deserunt mollit',
        observacoes: 'Nemo enim ipsam voluptatem quia voluptas sit',
    },
    {
        id: '5',
        status: 'Sobrestado',
        nup: '25000.914673/2023-41',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1074, dez/2025',
        assunto: 'Neque porro quisquam est qui dolorem ipsum',
        observacoes: null,
    },
    {
        id: '6',
        status: 'Sobrestado',
        nup: '25000.283751/2022-68',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1076, dez/2025',
        assunto: 'Quis autem vel eum iure reprehenderit qui',
        observacoes: null,
    },
    {
        id: '7',
        status: 'Área técnica retornou',
        nup: '25000.647029/2022-34',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1085, fev/2026',
        assunto: 'At vero eos et accusamus et iusto odio',
        observacoes: null,
    },
    {
        id: '8',
        status: 'Área técnica retornou',
        nup: '25000.519384/2021-77',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1084, fev/2026',
        assunto: 'Nam libero tempore cum soluta nobis eligendi',
        observacoes: 'Temporibus autem quibusdam et aut officiis debitis',
    },
    {
        id: '9',
        status: 'Finalizado',
        nup: '25000.762840/2025-15',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 1023, julho 2025',
        assunto: 'Itaque earum rerum hic tenetur a sapiente',
        observacoes: 'Totam rem aperiam eaque ipsa quae ab illo',
    },
    {
        id: '10',
        status: 'Finalizado',
        nup: '25000.438291/2022-56',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 732, mai/2022',
        assunto: 'Nisi ut aliquid ex ea commodi consequatur',
        observacoes: 'Quis nostrum exercitationem ullam corporis suscipit',
    },
    {
        id: '11',
        status: 'Finalizado',
        nup: '25000.873614/2021-29',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 762, ago/2022',
        assunto: 'Laboriosam nisi ut aliquid ex ea commodi',
        observacoes: 'Quia consequuntur magni dolores eos qui ratione',
    },
    {
        id: '12',
        status: 'Finalizado',
        nup: '25000.194758/2021-43',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 733, mai/2022',
        assunto: 'Voluptatem sequi nesciunt neque porro quisquam',
        observacoes: 'Ut labore et dolore magnam aliquam quaerat',
    },
    {
        id: '13',
        status: 'Finalizado',
        nup: '25000.536921/2024-88',
        tipo: 'novo',
        relatorio: 'Relatório nº 981, mar/2025',
        assunto: 'Accusantium doloremque laudantium totam rem aperiam',
        observacoes: 'Eaque ipsa quae ab illo inventore veritatis',
    },
    {
        id: '14',
        status: 'Sobrestado',
        nup: '25000.071483/2020-61',
        tipo: 'atualizacao',
        relatorio: 'Relatório nº 612, jun/2021',
        assunto: 'Beatae vitae dicta sunt explicabo nemo enim',
        observacoes: 'Ipsam voluptatem quia voluptas sit aspernatur',
    },
    {
        id: '15',
        status: 'Área técnica retornou',
        nup: '25000.923756/2023-39',
        tipo: 'novo',
        relatorio: 'Relatório nº 1031, ago/2025',
        assunto: 'Architecto beatae vitae dicta sunt explicabo',
        observacoes: 'Nemo enim ipsam voluptatem quia voluptas sit',
    },
];
